### ISSUE TITLE
Add code example "Drupal 8 Hello World module with multilingual support"

### ISSUE THREAD

**Issue by kalabro** [hechoendrupal/drupal8-links#13]
http://drupal.stackexchange.com/questions/87922/add-multilingual-support-to-drupal-8-hello-world-module/87923#87923

Comment published at http://hojtsy.hu/comment/19421#comment-19421

**Comment by jmolivas** [comment]
Thanks for the PR commit on e75b47c04c7e4daeff69edbaf8b91dbbc09287ce
